# yamllint disable rule:key-duplicates
sudo: required
install: true

services:
- docker

script: auto/verify-html
script: auto/verify-spelling

jobs:
  include:
  - stage: Test
    script: auto/verify-html
  -
    script: auto/verify-spelling
