# yamllint disable rule:key-duplicates
sudo: required
install: true

services:
- docker

script: auto/verify/verify-html
script: auto/verify-spelling
script: auto/verify-yaml
script: auto/verify-docker
script: auto/verify-shell

jobs:
  include:
  - stage: Test
    script: auto/verify/verify-html
  -
    script: auto/verify/verify-spelling
  -
    script: auto/verify/verify-yaml
  -
    script: auto/verify/verify-docker
  -
    script: auto/verify/verify-shell
