title: This Is The World
baseurl: ""
exclude: ['auto', 'support']
analytics_id: UA-99830249-1
url: https://thisistheworld.net

# this will strip all pages of the .html extension when jekyll generates a url
permalink: /:categories/:year/:month/:day/:title

plugins:
- jekyll-sitemap

# Build settings
markdown: kramdown

sass:
  sass_dir: _sass
  style: :compressed
