title: This Is The World
baseurl: ""
exclude: ['auto', 'support']
analytics_id: UA-99830249-1
url: https://thisistheworld.net

# Build settings
markdown: kramdown

sass:
  sass_dir: _sass
  style: :compressed
