version: '2'

services:
  dev:
    build:
      dockerfile: support/dev/Dockerfile
      context: .
    working_dir: /work
    command: support/dev/run
    volumes:
      - .:/work
      - ruby2.5-gem-cache:/usr/local/bundle
    ports:
      - 4000:4000
  prod:
    environment:
      - JEKYLL_ENV=production
    extends:
      service: dev

volumes:
  ruby2.5-gem-cache:
    external: true
